repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: name-tests-test
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: v1.13.0
    hooks:
      - id: basedpyright
        language:
          system # somehow the basedpyright app installed via the commit hooks does not work,
          # setting this does now (per my knowledge) use the system one (= the one from the active venv)
  - repo: https://github.com/fpgmaas/deptry.git
    rev: "0.21.2"
    hooks:
      - id: deptry
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.25
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        args: ["--verbose"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
